services:
  website:
    build:
      context: .
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@127.0.0.1:5932/sluggers_super_draft"
      NODE_ENV: "production"

  db:
    image: postgres:17
    ports:
      - "127.0.0.1:5932:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sluggers_super_draft

volumes:
  db:
